# Generated by Django 3.1.1 on 2020-09-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emi_status',
            field=models.BooleanField(default=True),
        ),
    ]
